/*
 * This file is generated by jOOQ.
 */
package me.ave.inventory.jooq.codegen.tables.daos


import javax.annotation.processing.Generated

import kotlin.collections.List

import me.ave.inventory.jooq.codegen.tables.Unassignedpackets
import me.ave.inventory.jooq.codegen.tables.records.UnassignedpacketsRecord

import org.jooq.Configuration
import org.jooq.impl.DAOImpl


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.19.7",
        "schema version:public_2"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("UNCHECKED_CAST")
open class UnassignedpacketsDao(configuration: Configuration?) : DAOImpl<UnassignedpacketsRecord, me.ave.inventory.jooq.codegen.tables.pojos.Unassignedpackets, Int>(Unassignedpackets.UNASSIGNEDPACKETS, me.ave.inventory.jooq.codegen.tables.pojos.Unassignedpackets::class.java, configuration) {

    /**
     * Create a new UnassignedpacketsDao without any configuration
     */
    constructor(): this(null)

    override fun getId(o: me.ave.inventory.jooq.codegen.tables.pojos.Unassignedpackets): Int? = o.id

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfId(lowerInclusive: Int?, upperInclusive: Int?): List<me.ave.inventory.jooq.codegen.tables.pojos.Unassignedpackets> = fetchRange(Unassignedpackets.UNASSIGNEDPACKETS.ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    fun fetchById(vararg values: Int): List<me.ave.inventory.jooq.codegen.tables.pojos.Unassignedpackets> = fetch(Unassignedpackets.UNASSIGNEDPACKETS.ID, *values.toTypedArray())

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    fun fetchOneById(value: Int): me.ave.inventory.jooq.codegen.tables.pojos.Unassignedpackets? = fetchOne(Unassignedpackets.UNASSIGNEDPACKETS.ID, value)

    /**
     * Fetch records that have <code>rfid BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfRfid(lowerInclusive: String?, upperInclusive: String?): List<me.ave.inventory.jooq.codegen.tables.pojos.Unassignedpackets> = fetchRange(Unassignedpackets.UNASSIGNEDPACKETS.RFID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>rfid IN (values)</code>
     */
    fun fetchByRfid(vararg values: String): List<me.ave.inventory.jooq.codegen.tables.pojos.Unassignedpackets> = fetch(Unassignedpackets.UNASSIGNEDPACKETS.RFID, *values)
}
