/*
 * This file is generated by jOOQ.
 */
package me.ave.inventory.jooq.codegen.tables


import javax.annotation.processing.Generated

import kotlin.collections.Collection

import me.ave.inventory.jooq.codegen.Public
import me.ave.inventory.jooq.codegen.keys.FLOOR_PKEY
import me.ave.inventory.jooq.codegen.keys.ROOM__FK_ROOMFLOOR
import me.ave.inventory.jooq.codegen.tables.Room.RoomPath
import me.ave.inventory.jooq.codegen.tables.records.FloorRecord

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.19.7",
        "schema version:public_2"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("UNCHECKED_CAST")
open class Floor(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, FloorRecord>?,
    parentPath: InverseForeignKey<out Record, FloorRecord>?,
    aliased: Table<FloorRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<FloorRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.floor</code>
         */
        val FLOOR: Floor = Floor()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<FloorRecord> = FloorRecord::class.java

    /**
     * The column <code>public.floor.id</code>.
     */
    val ID: TableField<FloorRecord, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.floor.name</code>.
     */
    val NAME: TableField<FloorRecord, String?> = createField(DSL.name("name"), SQLDataType.VARCHAR(50).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<FloorRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<FloorRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<FloorRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.floor</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.floor</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.floor</code> table reference
     */
    constructor(): this(DSL.name("floor"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, FloorRecord>?, parentPath: InverseForeignKey<out Record, FloorRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, FLOOR, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class FloorPath : Floor, Path<FloorRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, FloorRecord>?, parentPath: InverseForeignKey<out Record, FloorRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<FloorRecord>): super(alias, aliased)
        override fun `as`(alias: String): FloorPath = FloorPath(DSL.name(alias), this)
        override fun `as`(alias: Name): FloorPath = FloorPath(alias, this)
        override fun `as`(alias: Table<*>): FloorPath = FloorPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<FloorRecord> = FLOOR_PKEY

    private lateinit var _room: RoomPath

    /**
     * Get the implicit to-many join path to the <code>public.room</code> table
     */
    fun room(): RoomPath {
        if (!this::_room.isInitialized)
            _room = RoomPath(this, null, ROOM__FK_ROOMFLOOR.inverseKey)

        return _room;
    }

    val room: RoomPath
        get(): RoomPath = room()
    override fun `as`(alias: String): Floor = Floor(DSL.name(alias), this)
    override fun `as`(alias: Name): Floor = Floor(alias, this)
    override fun `as`(alias: Table<*>): Floor = Floor(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Floor = Floor(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Floor = Floor(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Floor = Floor(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Floor = Floor(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Floor = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Floor = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Floor = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Floor = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Floor = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Floor = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Floor = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Floor = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Floor = where(DSL.notExists(select))
}
