/*
 * This file is generated by jOOQ.
 */
package me.ave.inventory.jooq.codegen.tables


import javax.annotation.processing.Generated

import kotlin.collections.Collection
import kotlin.collections.List

import me.ave.inventory.jooq.codegen.Public
import me.ave.inventory.jooq.codegen.keys.MACHINEINFO_PKEY
import me.ave.inventory.jooq.codegen.keys.MACHINETOLOCATION__FK_MACHINEMODEL
import me.ave.inventory.jooq.codegen.keys.MACHINE__FK_MACHINEINFO
import me.ave.inventory.jooq.codegen.keys.MAINTENANCERECORD__FK_MAINTAININFO
import me.ave.inventory.jooq.codegen.keys.SPAREPARTINFO__FK_CODEINFO
import me.ave.inventory.jooq.codegen.keys.UQ_MACHINENAME
import me.ave.inventory.jooq.codegen.tables.Location.LocationPath
import me.ave.inventory.jooq.codegen.tables.Machine.MachinePath
import me.ave.inventory.jooq.codegen.tables.Machinetolocation.MachinetolocationPath
import me.ave.inventory.jooq.codegen.tables.Maintenancerecord.MaintenancerecordPath
import me.ave.inventory.jooq.codegen.tables.Sparepartinfo.SparepartinfoPath
import me.ave.inventory.jooq.codegen.tables.records.MachineinfoRecord

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.19.7",
        "schema version:public_2"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("UNCHECKED_CAST")
open class Machineinfo(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, MachineinfoRecord>?,
    parentPath: InverseForeignKey<out Record, MachineinfoRecord>?,
    aliased: Table<MachineinfoRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<MachineinfoRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.machineinfo</code>
         */
        val MACHINEINFO: Machineinfo = Machineinfo()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<MachineinfoRecord> = MachineinfoRecord::class.java

    /**
     * The column <code>public.machineinfo.model</code>.
     */
    val MODEL: TableField<MachineinfoRecord, String?> = createField(DSL.name("model"), SQLDataType.VARCHAR(3).nullable(false), this, "")

    /**
     * The column <code>public.machineinfo.name</code>.
     */
    val NAME: TableField<MachineinfoRecord, String?> = createField(DSL.name("name"), SQLDataType.VARCHAR(50).nullable(false), this, "")

    /**
     * The column <code>public.machineinfo.maker</code>.
     */
    val MAKER: TableField<MachineinfoRecord, String?> = createField(DSL.name("maker"), SQLDataType.VARCHAR(100).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<MachineinfoRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<MachineinfoRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<MachineinfoRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.machineinfo</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.machineinfo</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.machineinfo</code> table reference
     */
    constructor(): this(DSL.name("machineinfo"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, MachineinfoRecord>?, parentPath: InverseForeignKey<out Record, MachineinfoRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, MACHINEINFO, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class MachineinfoPath : Machineinfo, Path<MachineinfoRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, MachineinfoRecord>?, parentPath: InverseForeignKey<out Record, MachineinfoRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<MachineinfoRecord>): super(alias, aliased)
        override fun `as`(alias: String): MachineinfoPath = MachineinfoPath(DSL.name(alias), this)
        override fun `as`(alias: Name): MachineinfoPath = MachineinfoPath(alias, this)
        override fun `as`(alias: Table<*>): MachineinfoPath = MachineinfoPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<MachineinfoRecord> = MACHINEINFO_PKEY
    override fun getUniqueKeys(): List<UniqueKey<MachineinfoRecord>> = listOf(UQ_MACHINENAME)

    private lateinit var _machine: MachinePath

    /**
     * Get the implicit to-many join path to the <code>public.machine</code>
     * table
     */
    fun machine(): MachinePath {
        if (!this::_machine.isInitialized)
            _machine = MachinePath(this, null, MACHINE__FK_MACHINEINFO.inverseKey)

        return _machine;
    }

    val machine: MachinePath
        get(): MachinePath = machine()

    private lateinit var _machinetolocation: MachinetolocationPath

    /**
     * Get the implicit to-many join path to the
     * <code>public.machinetolocation</code> table
     */
    fun machinetolocation(): MachinetolocationPath {
        if (!this::_machinetolocation.isInitialized)
            _machinetolocation = MachinetolocationPath(this, null, MACHINETOLOCATION__FK_MACHINEMODEL.inverseKey)

        return _machinetolocation;
    }

    val machinetolocation: MachinetolocationPath
        get(): MachinetolocationPath = machinetolocation()

    private lateinit var _maintenancerecord: MaintenancerecordPath

    /**
     * Get the implicit to-many join path to the
     * <code>public.maintenancerecord</code> table
     */
    fun maintenancerecord(): MaintenancerecordPath {
        if (!this::_maintenancerecord.isInitialized)
            _maintenancerecord = MaintenancerecordPath(this, null, MAINTENANCERECORD__FK_MAINTAININFO.inverseKey)

        return _maintenancerecord;
    }

    val maintenancerecord: MaintenancerecordPath
        get(): MaintenancerecordPath = maintenancerecord()

    private lateinit var _sparepartinfo: SparepartinfoPath

    /**
     * Get the implicit to-many join path to the
     * <code>public.sparepartinfo</code> table
     */
    fun sparepartinfo(): SparepartinfoPath {
        if (!this::_sparepartinfo.isInitialized)
            _sparepartinfo = SparepartinfoPath(this, null, SPAREPARTINFO__FK_CODEINFO.inverseKey)

        return _sparepartinfo;
    }

    val sparepartinfo: SparepartinfoPath
        get(): SparepartinfoPath = sparepartinfo()

    /**
     * Get the implicit many-to-many join path to the
     * <code>public.location</code> table
     */
    val location: LocationPath
        get(): LocationPath = machinetolocation().location()
    override fun `as`(alias: String): Machineinfo = Machineinfo(DSL.name(alias), this)
    override fun `as`(alias: Name): Machineinfo = Machineinfo(alias, this)
    override fun `as`(alias: Table<*>): Machineinfo = Machineinfo(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Machineinfo = Machineinfo(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Machineinfo = Machineinfo(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Machineinfo = Machineinfo(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Machineinfo = Machineinfo(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Machineinfo = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Machineinfo = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Machineinfo = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Machineinfo = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Machineinfo = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Machineinfo = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Machineinfo = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Machineinfo = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Machineinfo = where(DSL.notExists(select))
}
