/*
 * This file is generated by jOOQ.
 */
package me.ave.inventory.jooq.codegen.tables


import javax.annotation.processing.Generated

import kotlin.collections.Collection
import kotlin.collections.List

import me.ave.inventory.jooq.codegen.Public
import me.ave.inventory.jooq.codegen.enums.PacketType
import me.ave.inventory.jooq.codegen.keys.PACKETRECORD_PKEY
import me.ave.inventory.jooq.codegen.keys.PACKETRECORD__FK_LOCATION
import me.ave.inventory.jooq.codegen.keys.PACKETRECORD__FK_PACKETCODE
import me.ave.inventory.jooq.codegen.keys.USEDPACKETRECORD__FK_PACKETRECORD
import me.ave.inventory.jooq.codegen.tables.Location.LocationPath
import me.ave.inventory.jooq.codegen.tables.Sparepartinfo.SparepartinfoPath
import me.ave.inventory.jooq.codegen.tables.Usedpacketrecord.UsedpacketrecordPath
import me.ave.inventory.jooq.codegen.tables.records.PacketrecordRecord

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.19.7",
        "schema version:public_2"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("UNCHECKED_CAST")
open class Packetrecord(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, PacketrecordRecord>?,
    parentPath: InverseForeignKey<out Record, PacketrecordRecord>?,
    aliased: Table<PacketrecordRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<PacketrecordRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.packetrecord</code>
         */
        val PACKETRECORD: Packetrecord = Packetrecord()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<PacketrecordRecord> = PacketrecordRecord::class.java

    /**
     * The column <code>public.packetrecord.id</code>.
     */
    val ID: TableField<PacketrecordRecord, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.packetrecord.code</code>.
     */
    val CODE: TableField<PacketrecordRecord, String?> = createField(DSL.name("code"), SQLDataType.VARCHAR(20).nullable(false), this, "")

    /**
     * The column <code>public.packetrecord.rfid</code>.
     */
    val RFID: TableField<PacketrecordRecord, String?> = createField(DSL.name("rfid"), SQLDataType.VARCHAR(30).nullable(false), this, "")

    /**
     * The column <code>public.packetrecord.quantity</code>.
     */
    val QUANTITY: TableField<PacketrecordRecord, Int?> = createField(DSL.name("quantity"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.packetrecord.type</code>.
     */
    val TYPE: TableField<PacketrecordRecord, PacketType?> = createField(DSL.name("type"), SQLDataType.VARCHAR.nullable(false).asEnumDataType(PacketType::class.java), this, "")

    /**
     * The column <code>public.packetrecord.location_id</code>.
     */
    val LOCATION_ID: TableField<PacketrecordRecord, Int?> = createField(DSL.name("location_id"), SQLDataType.INTEGER.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<PacketrecordRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<PacketrecordRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<PacketrecordRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.packetrecord</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.packetrecord</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.packetrecord</code> table reference
     */
    constructor(): this(DSL.name("packetrecord"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, PacketrecordRecord>?, parentPath: InverseForeignKey<out Record, PacketrecordRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, PACKETRECORD, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class PacketrecordPath : Packetrecord, Path<PacketrecordRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, PacketrecordRecord>?, parentPath: InverseForeignKey<out Record, PacketrecordRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<PacketrecordRecord>): super(alias, aliased)
        override fun `as`(alias: String): PacketrecordPath = PacketrecordPath(DSL.name(alias), this)
        override fun `as`(alias: Name): PacketrecordPath = PacketrecordPath(alias, this)
        override fun `as`(alias: Table<*>): PacketrecordPath = PacketrecordPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<PacketrecordRecord> = PACKETRECORD_PKEY
    override fun getReferences(): List<ForeignKey<PacketrecordRecord, *>> = listOf(PACKETRECORD__FK_PACKETCODE, PACKETRECORD__FK_LOCATION)

    private lateinit var _sparepartinfo: SparepartinfoPath

    /**
     * Get the implicit join path to the <code>public.sparepartinfo</code>
     * table.
     */
    fun sparepartinfo(): SparepartinfoPath {
        if (!this::_sparepartinfo.isInitialized)
            _sparepartinfo = SparepartinfoPath(this, PACKETRECORD__FK_PACKETCODE, null)

        return _sparepartinfo;
    }

    val sparepartinfo: SparepartinfoPath
        get(): SparepartinfoPath = sparepartinfo()

    private lateinit var _location: LocationPath

    /**
     * Get the implicit join path to the <code>public.location</code> table.
     */
    fun location(): LocationPath {
        if (!this::_location.isInitialized)
            _location = LocationPath(this, PACKETRECORD__FK_LOCATION, null)

        return _location;
    }

    val location: LocationPath
        get(): LocationPath = location()

    private lateinit var _usedpacketrecord: UsedpacketrecordPath

    /**
     * Get the implicit to-many join path to the
     * <code>public.usedpacketrecord</code> table
     */
    fun usedpacketrecord(): UsedpacketrecordPath {
        if (!this::_usedpacketrecord.isInitialized)
            _usedpacketrecord = UsedpacketrecordPath(this, null, USEDPACKETRECORD__FK_PACKETRECORD.inverseKey)

        return _usedpacketrecord;
    }

    val usedpacketrecord: UsedpacketrecordPath
        get(): UsedpacketrecordPath = usedpacketrecord()
    override fun `as`(alias: String): Packetrecord = Packetrecord(DSL.name(alias), this)
    override fun `as`(alias: Name): Packetrecord = Packetrecord(alias, this)
    override fun `as`(alias: Table<*>): Packetrecord = Packetrecord(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Packetrecord = Packetrecord(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Packetrecord = Packetrecord(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Packetrecord = Packetrecord(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Packetrecord = Packetrecord(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Packetrecord = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Packetrecord = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Packetrecord = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Packetrecord = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Packetrecord = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Packetrecord = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Packetrecord = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Packetrecord = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Packetrecord = where(DSL.notExists(select))
}
