/*
 * This file is generated by jOOQ.
 */
package me.ave.inventory.jooq.codegen.tables


import javax.annotation.processing.Generated

import kotlin.collections.Collection
import kotlin.collections.List

import me.ave.inventory.jooq.codegen.Public
import me.ave.inventory.jooq.codegen.enums.ScheduleType
import me.ave.inventory.jooq.codegen.keys.JOB__FK_JOBSCHEDULE
import me.ave.inventory.jooq.codegen.keys.SCHEDULEINFO_PKEY
import me.ave.inventory.jooq.codegen.keys.UQ_SCHEDULETYPE
import me.ave.inventory.jooq.codegen.tables.Job.JobPath
import me.ave.inventory.jooq.codegen.tables.records.ScheduleinfoRecord

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.19.7",
        "schema version:public_2"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("UNCHECKED_CAST")
open class Scheduleinfo(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, ScheduleinfoRecord>?,
    parentPath: InverseForeignKey<out Record, ScheduleinfoRecord>?,
    aliased: Table<ScheduleinfoRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<ScheduleinfoRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.scheduleinfo</code>
         */
        val SCHEDULEINFO: Scheduleinfo = Scheduleinfo()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<ScheduleinfoRecord> = ScheduleinfoRecord::class.java

    /**
     * The column <code>public.scheduleinfo.id</code>.
     */
    val ID: TableField<ScheduleinfoRecord, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.scheduleinfo.type</code>.
     */
    val TYPE: TableField<ScheduleinfoRecord, ScheduleType?> = createField(DSL.name("type"), SQLDataType.VARCHAR.nullable(false).asEnumDataType(ScheduleType::class.java), this, "")

    /**
     * The column <code>public.scheduleinfo.delay</code>.
     */
    val DELAY: TableField<ScheduleinfoRecord, Int?> = createField(DSL.name("delay"), SQLDataType.INTEGER.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<ScheduleinfoRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<ScheduleinfoRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<ScheduleinfoRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.scheduleinfo</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.scheduleinfo</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.scheduleinfo</code> table reference
     */
    constructor(): this(DSL.name("scheduleinfo"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, ScheduleinfoRecord>?, parentPath: InverseForeignKey<out Record, ScheduleinfoRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, SCHEDULEINFO, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class ScheduleinfoPath : Scheduleinfo, Path<ScheduleinfoRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, ScheduleinfoRecord>?, parentPath: InverseForeignKey<out Record, ScheduleinfoRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<ScheduleinfoRecord>): super(alias, aliased)
        override fun `as`(alias: String): ScheduleinfoPath = ScheduleinfoPath(DSL.name(alias), this)
        override fun `as`(alias: Name): ScheduleinfoPath = ScheduleinfoPath(alias, this)
        override fun `as`(alias: Table<*>): ScheduleinfoPath = ScheduleinfoPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIdentity(): Identity<ScheduleinfoRecord, Int?> = super.getIdentity() as Identity<ScheduleinfoRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<ScheduleinfoRecord> = SCHEDULEINFO_PKEY
    override fun getUniqueKeys(): List<UniqueKey<ScheduleinfoRecord>> = listOf(UQ_SCHEDULETYPE)

    private lateinit var _job: JobPath

    /**
     * Get the implicit to-many join path to the <code>public.job</code> table
     */
    fun job(): JobPath {
        if (!this::_job.isInitialized)
            _job = JobPath(this, null, JOB__FK_JOBSCHEDULE.inverseKey)

        return _job;
    }

    val job: JobPath
        get(): JobPath = job()
    override fun `as`(alias: String): Scheduleinfo = Scheduleinfo(DSL.name(alias), this)
    override fun `as`(alias: Name): Scheduleinfo = Scheduleinfo(alias, this)
    override fun `as`(alias: Table<*>): Scheduleinfo = Scheduleinfo(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Scheduleinfo = Scheduleinfo(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Scheduleinfo = Scheduleinfo(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Scheduleinfo = Scheduleinfo(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Scheduleinfo = Scheduleinfo(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Scheduleinfo = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Scheduleinfo = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Scheduleinfo = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Scheduleinfo = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Scheduleinfo = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Scheduleinfo = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Scheduleinfo = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Scheduleinfo = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Scheduleinfo = where(DSL.notExists(select))
}
