/*
 * This file is generated by jOOQ.
 */
package me.ave.inventory.jooq.codegen.tables


import javax.annotation.processing.Generated

import kotlin.collections.Collection
import kotlin.collections.List

import me.ave.inventory.jooq.codegen.Public
import me.ave.inventory.jooq.codegen.keys.USEDPACKETRECORD_PKEY
import me.ave.inventory.jooq.codegen.keys.USEDPACKETRECORD__FK_PACKETRECORD
import me.ave.inventory.jooq.codegen.tables.Packetrecord.PacketrecordPath
import me.ave.inventory.jooq.codegen.tables.records.UsedpacketrecordRecord

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.19.7",
        "schema version:public_2"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("UNCHECKED_CAST")
open class Usedpacketrecord(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, UsedpacketrecordRecord>?,
    parentPath: InverseForeignKey<out Record, UsedpacketrecordRecord>?,
    aliased: Table<UsedpacketrecordRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<UsedpacketrecordRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.usedpacketrecord</code>
         */
        val USEDPACKETRECORD: Usedpacketrecord = Usedpacketrecord()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<UsedpacketrecordRecord> = UsedpacketrecordRecord::class.java

    /**
     * The column <code>public.usedpacketrecord.id</code>.
     */
    val ID: TableField<UsedpacketrecordRecord, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.usedpacketrecord.packet_id</code>.
     */
    val PACKET_ID: TableField<UsedpacketrecordRecord, Int?> = createField(DSL.name("packet_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.usedpacketrecord.maintenance_id</code>.
     */
    val MAINTENANCE_ID: TableField<UsedpacketrecordRecord, Int?> = createField(DSL.name("maintenance_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.usedpacketrecord.quantity</code>.
     */
    val QUANTITY: TableField<UsedpacketrecordRecord, Int?> = createField(DSL.name("quantity"), SQLDataType.INTEGER.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<UsedpacketrecordRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<UsedpacketrecordRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<UsedpacketrecordRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.usedpacketrecord</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.usedpacketrecord</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.usedpacketrecord</code> table reference
     */
    constructor(): this(DSL.name("usedpacketrecord"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, UsedpacketrecordRecord>?, parentPath: InverseForeignKey<out Record, UsedpacketrecordRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, USEDPACKETRECORD, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class UsedpacketrecordPath : Usedpacketrecord, Path<UsedpacketrecordRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, UsedpacketrecordRecord>?, parentPath: InverseForeignKey<out Record, UsedpacketrecordRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<UsedpacketrecordRecord>): super(alias, aliased)
        override fun `as`(alias: String): UsedpacketrecordPath = UsedpacketrecordPath(DSL.name(alias), this)
        override fun `as`(alias: Name): UsedpacketrecordPath = UsedpacketrecordPath(alias, this)
        override fun `as`(alias: Table<*>): UsedpacketrecordPath = UsedpacketrecordPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIdentity(): Identity<UsedpacketrecordRecord, Int?> = super.getIdentity() as Identity<UsedpacketrecordRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<UsedpacketrecordRecord> = USEDPACKETRECORD_PKEY
    override fun getReferences(): List<ForeignKey<UsedpacketrecordRecord, *>> = listOf(USEDPACKETRECORD__FK_PACKETRECORD)

    private lateinit var _packetrecord: PacketrecordPath

    /**
     * Get the implicit join path to the <code>public.packetrecord</code> table.
     */
    fun packetrecord(): PacketrecordPath {
        if (!this::_packetrecord.isInitialized)
            _packetrecord = PacketrecordPath(this, USEDPACKETRECORD__FK_PACKETRECORD, null)

        return _packetrecord;
    }

    val packetrecord: PacketrecordPath
        get(): PacketrecordPath = packetrecord()
    override fun `as`(alias: String): Usedpacketrecord = Usedpacketrecord(DSL.name(alias), this)
    override fun `as`(alias: Name): Usedpacketrecord = Usedpacketrecord(alias, this)
    override fun `as`(alias: Table<*>): Usedpacketrecord = Usedpacketrecord(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Usedpacketrecord = Usedpacketrecord(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Usedpacketrecord = Usedpacketrecord(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Usedpacketrecord = Usedpacketrecord(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Usedpacketrecord = Usedpacketrecord(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Usedpacketrecord = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Usedpacketrecord = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Usedpacketrecord = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Usedpacketrecord = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Usedpacketrecord = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Usedpacketrecord = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Usedpacketrecord = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Usedpacketrecord = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Usedpacketrecord = where(DSL.notExists(select))
}
