/*
 * This file is generated by jOOQ.
 */
package me.ave.inventory.jooq.codegen.tables.records


import javax.annotation.processing.Generated

import me.ave.inventory.jooq.codegen.enums.JobKind
import me.ave.inventory.jooq.codegen.enums.JobPlace
import me.ave.inventory.jooq.codegen.enums.Pic
import me.ave.inventory.jooq.codegen.tables.Job

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.19.7",
        "schema version:public_2"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("UNCHECKED_CAST")
open class JobRecord() : UpdatableRecordImpl<JobRecord>(Job.JOB) {

    open var pmsCode: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var description: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var place: JobPlace?
        set(value): Unit = set(2, value)
        get(): JobPlace? = get(2) as JobPlace?

    open var kind: JobKind?
        set(value): Unit = set(3, value)
        get(): JobKind? = get(3) as JobKind?

    open var scheduleKey: Int?
        set(value): Unit = set(4, value)
        get(): Int? = get(4) as Int?

    open var model: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    open var pic: Pic?
        set(value): Unit = set(6, value)
        get(): Pic? = get(6) as Pic?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    /**
     * Create a detached, initialised JobRecord
     */
    constructor(pmsCode: String? = null, description: String? = null, place: JobPlace? = null, kind: JobKind? = null, scheduleKey: Int? = null, model: String? = null, pic: Pic? = null): this() {
        this.pmsCode = pmsCode
        this.description = description
        this.place = place
        this.kind = kind
        this.scheduleKey = scheduleKey
        this.model = model
        this.pic = pic
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised JobRecord
     */
    constructor(value: me.ave.inventory.jooq.codegen.tables.pojos.Job?): this() {
        if (value != null) {
            this.pmsCode = value.pmsCode
            this.description = value.description
            this.place = value.place
            this.kind = value.kind
            this.scheduleKey = value.scheduleKey
            this.model = value.model
            this.pic = value.pic
            resetChangedOnNotNull()
        }
    }
}
