/*
 * This file is generated by jOOQ.
 */
package me.ave.inventory.jooq.codegen.tables.records


import javax.annotation.processing.Generated

import me.ave.inventory.jooq.codegen.tables.Machinetolocation

import org.jooq.impl.TableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.19.7",
        "schema version:public_2"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("UNCHECKED_CAST")
open class MachinetolocationRecord() : TableRecordImpl<MachinetolocationRecord>(Machinetolocation.MACHINETOLOCATION) {

    open var model: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var locationId: Int?
        set(value): Unit = set(1, value)
        get(): Int? = get(1) as Int?

    /**
     * Create a detached, initialised MachinetolocationRecord
     */
    constructor(model: String? = null, locationId: Int? = null): this() {
        this.model = model
        this.locationId = locationId
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised MachinetolocationRecord
     */
    constructor(value: me.ave.inventory.jooq.codegen.tables.pojos.Machinetolocation?): this() {
        if (value != null) {
            this.model = value.model
            this.locationId = value.locationId
            resetChangedOnNotNull()
        }
    }
}
