/*
 * This file is generated by jOOQ.
 */
package me.ave.inventory.jooq.codegen.tables.records


import javax.annotation.processing.Generated

import kotlinx.datetime.Instant

import me.ave.inventory.jooq.codegen.tables.Machine

import org.jooq.Record2
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.19.7",
        "schema version:public_2"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("UNCHECKED_CAST")
open class MachineRecord() : UpdatableRecordImpl<MachineRecord>(Machine.MACHINE) {

    open var model: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var machineNo: Int?
        set(value): Unit = set(1, value)
        get(): Int? = get(1) as Int?

    open var lastMaintenance: Instant?
        set(value): Unit = set(2, value)
        get(): Instant? = get(2) as Instant?

    open var avgRh: Int?
        set(value): Unit = set(3, value)
        get(): Int? = get(3) as Int?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record2<String?, Int?> = super.key() as Record2<String?, Int?>

    /**
     * Create a detached, initialised MachineRecord
     */
    constructor(model: String? = null, machineNo: Int? = null, lastMaintenance: Instant? = null, avgRh: Int? = null): this() {
        this.model = model
        this.machineNo = machineNo
        this.lastMaintenance = lastMaintenance
        this.avgRh = avgRh
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised MachineRecord
     */
    constructor(value: me.ave.inventory.jooq.codegen.tables.pojos.Machine?): this() {
        if (value != null) {
            this.model = value.model
            this.machineNo = value.machineNo
            this.lastMaintenance = value.lastMaintenance
            this.avgRh = value.avgRh
            resetChangedOnNotNull()
        }
    }
}
