/*
 * This file is generated by jOOQ.
 */
package me.ave.inventory.jooq.codegen.tables.records


import javax.annotation.processing.Generated

import me.ave.inventory.jooq.codegen.tables.Maintenanceupdatedpacket

import org.jooq.impl.TableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.19.7",
        "schema version:public_2"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("UNCHECKED_CAST")
open class MaintenanceupdatedpacketRecord() : TableRecordImpl<MaintenanceupdatedpacketRecord>(Maintenanceupdatedpacket.MAINTENANCEUPDATEDPACKET) {

    open var maintenanceId: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var sparePartCode: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var updatedQuantity: Int?
        set(value): Unit = set(2, value)
        get(): Int? = get(2) as Int?

    /**
     * Create a detached, initialised MaintenanceupdatedpacketRecord
     */
    constructor(maintenanceId: Int? = null, sparePartCode: String? = null, updatedQuantity: Int? = null): this() {
        this.maintenanceId = maintenanceId
        this.sparePartCode = sparePartCode
        this.updatedQuantity = updatedQuantity
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised MaintenanceupdatedpacketRecord
     */
    constructor(value: me.ave.inventory.jooq.codegen.tables.pojos.Maintenanceupdatedpacket?): this() {
        if (value != null) {
            this.maintenanceId = value.maintenanceId
            this.sparePartCode = value.sparePartCode
            this.updatedQuantity = value.updatedQuantity
            resetChangedOnNotNull()
        }
    }
}
