/*
 * This file is generated by jOOQ.
 */
package me.ave.inventory.jooq.codegen.tables.records


import javax.annotation.processing.Generated

import me.ave.inventory.jooq.codegen.tables.Room

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.19.7",
        "schema version:public_2"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("UNCHECKED_CAST")
open class RoomRecord() : UpdatableRecordImpl<RoomRecord>(Room.ROOM) {

    open var id: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var name: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var floor: Int?
        set(value): Unit = set(2, value)
        get(): Int? = get(2) as Int?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    /**
     * Create a detached, initialised RoomRecord
     */
    constructor(id: Int? = null, name: String? = null, floor: Int? = null): this() {
        this.id = id
        this.name = name
        this.floor = floor
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised RoomRecord
     */
    constructor(value: me.ave.inventory.jooq.codegen.tables.pojos.Room?): this() {
        if (value != null) {
            this.id = value.id
            this.name = value.name
            this.floor = value.floor
            resetChangedOnNotNull()
        }
    }
}
