/*
 * This file is generated by jOOQ.
 */
package me.ave.inventory.jooq.codegen.tables.records


import javax.annotation.processing.Generated

import me.ave.inventory.jooq.codegen.tables.Unassignedpackets

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.19.7",
        "schema version:public_2"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("UNCHECKED_CAST")
open class UnassignedpacketsRecord() : UpdatableRecordImpl<UnassignedpacketsRecord>(Unassignedpackets.UNASSIGNEDPACKETS) {

    open var id: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var rfid: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    /**
     * Create a detached, initialised UnassignedpacketsRecord
     */
    constructor(id: Int? = null, rfid: String? = null): this() {
        this.id = id
        this.rfid = rfid
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised UnassignedpacketsRecord
     */
    constructor(value: me.ave.inventory.jooq.codegen.tables.pojos.Unassignedpackets?): this() {
        if (value != null) {
            this.id = value.id
            this.rfid = value.rfid
            resetChangedOnNotNull()
        }
    }
}
