/*
 * This file is generated by jOOQ.
 */
package me.ave.inventory.jooq.codegen.tables.records


import javax.annotation.processing.Generated

import me.ave.inventory.jooq.codegen.tables.Usedpacketrecord

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.19.7",
        "schema version:public_2"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("UNCHECKED_CAST")
open class UsedpacketrecordRecord() : UpdatableRecordImpl<UsedpacketrecordRecord>(Usedpacketrecord.USEDPACKETRECORD) {

    open var id: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var packetId: Int?
        set(value): Unit = set(1, value)
        get(): Int? = get(1) as Int?

    open var maintenanceId: Int?
        set(value): Unit = set(2, value)
        get(): Int? = get(2) as Int?

    open var quantity: Int?
        set(value): Unit = set(3, value)
        get(): Int? = get(3) as Int?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    /**
     * Create a detached, initialised UsedpacketrecordRecord
     */
    constructor(id: Int? = null, packetId: Int? = null, maintenanceId: Int? = null, quantity: Int? = null): this() {
        this.id = id
        this.packetId = packetId
        this.maintenanceId = maintenanceId
        this.quantity = quantity
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised UsedpacketrecordRecord
     */
    constructor(value: me.ave.inventory.jooq.codegen.tables.pojos.Usedpacketrecord?): this() {
        if (value != null) {
            this.id = value.id
            this.packetId = value.packetId
            this.maintenanceId = value.maintenanceId
            this.quantity = value.quantity
            resetChangedOnNotNull()
        }
    }
}
