/*
 * This file is generated by jOOQ.
 */
package me.ave.inventory.jooq.codegen.tables.references


import me.ave.inventory.jooq.codegen.tables.Databasechangelog
import me.ave.inventory.jooq.codegen.tables.Databasechangeloglock
import me.ave.inventory.jooq.codegen.tables.Floor
import me.ave.inventory.jooq.codegen.tables.Job
import me.ave.inventory.jooq.codegen.tables.Jobtosparepart
import me.ave.inventory.jooq.codegen.tables.Location
import me.ave.inventory.jooq.codegen.tables.Machine
import me.ave.inventory.jooq.codegen.tables.Machineinfo
import me.ave.inventory.jooq.codegen.tables.Machinetolocation
import me.ave.inventory.jooq.codegen.tables.Maintenancerecord
import me.ave.inventory.jooq.codegen.tables.Maintenanceupdatedpacket
import me.ave.inventory.jooq.codegen.tables.Packetrecord
import me.ave.inventory.jooq.codegen.tables.Room
import me.ave.inventory.jooq.codegen.tables.Scheduleinfo
import me.ave.inventory.jooq.codegen.tables.Sparepartinfo
import me.ave.inventory.jooq.codegen.tables.Unassignedpackets
import me.ave.inventory.jooq.codegen.tables.Usedpacketrecord



/**
 * The table <code>public.databasechangelog</code>.
 */
val DATABASECHANGELOG: Databasechangelog = Databasechangelog.DATABASECHANGELOG

/**
 * The table <code>public.databasechangeloglock</code>.
 */
val DATABASECHANGELOGLOCK: Databasechangeloglock = Databasechangeloglock.DATABASECHANGELOGLOCK

/**
 * The table <code>public.floor</code>.
 */
val FLOOR: Floor = Floor.FLOOR

/**
 * The table <code>public.job</code>.
 */
val JOB: Job = Job.JOB

/**
 * The table <code>public.jobtosparepart</code>.
 */
val JOBTOSPAREPART: Jobtosparepart = Jobtosparepart.JOBTOSPAREPART

/**
 * The table <code>public.location</code>.
 */
val LOCATION: Location = Location.LOCATION

/**
 * The table <code>public.machine</code>.
 */
val MACHINE: Machine = Machine.MACHINE

/**
 * The table <code>public.machineinfo</code>.
 */
val MACHINEINFO: Machineinfo = Machineinfo.MACHINEINFO

/**
 * The table <code>public.machinetolocation</code>.
 */
val MACHINETOLOCATION: Machinetolocation = Machinetolocation.MACHINETOLOCATION

/**
 * The table <code>public.maintenancerecord</code>.
 */
val MAINTENANCERECORD: Maintenancerecord = Maintenancerecord.MAINTENANCERECORD

/**
 * The table <code>public.maintenanceupdatedpacket</code>.
 */
val MAINTENANCEUPDATEDPACKET: Maintenanceupdatedpacket = Maintenanceupdatedpacket.MAINTENANCEUPDATEDPACKET

/**
 * The table <code>public.packetrecord</code>.
 */
val PACKETRECORD: Packetrecord = Packetrecord.PACKETRECORD

/**
 * The table <code>public.room</code>.
 */
val ROOM: Room = Room.ROOM

/**
 * The table <code>public.scheduleinfo</code>.
 */
val SCHEDULEINFO: Scheduleinfo = Scheduleinfo.SCHEDULEINFO

/**
 * The table <code>public.sparepartinfo</code>.
 */
val SPAREPARTINFO: Sparepartinfo = Sparepartinfo.SPAREPARTINFO

/**
 * The table <code>public.unassignedpackets</code>.
 */
val UNASSIGNEDPACKETS: Unassignedpackets = Unassignedpackets.UNASSIGNEDPACKETS

/**
 * The table <code>public.usedpacketrecord</code>.
 */
val USEDPACKETRECORD: Usedpacketrecord = Usedpacketrecord.USEDPACKETRECORD
