/*
 * This file is generated by jOOQ.
 */
package me.ave.inventory.jooq.codegen.tables.pojos


import java.io.Serializable

import javax.annotation.processing.Generated

import me.ave.inventory.jooq.codegen.enums.JobKind
import me.ave.inventory.jooq.codegen.enums.JobPlace
import me.ave.inventory.jooq.codegen.enums.Pic


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.19.7",
        "schema version:public_2"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("UNCHECKED_CAST")
data class Job(
    var pmsCode: String? = null,
    var description: String? = null,
    var place: JobPlace? = null,
    var kind: JobKind? = null,
    var scheduleKey: Int? = null,
    var model: String? = null,
    var pic: Pic? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: Job = other as Job
        if (this.pmsCode == null) {
            if (o.pmsCode != null)
                return false
        }
        else if (this.pmsCode != o.pmsCode)
            return false
        if (this.description == null) {
            if (o.description != null)
                return false
        }
        else if (this.description != o.description)
            return false
        if (this.place == null) {
            if (o.place != null)
                return false
        }
        else if (this.place != o.place)
            return false
        if (this.kind == null) {
            if (o.kind != null)
                return false
        }
        else if (this.kind != o.kind)
            return false
        if (this.scheduleKey == null) {
            if (o.scheduleKey != null)
                return false
        }
        else if (this.scheduleKey != o.scheduleKey)
            return false
        if (this.model == null) {
            if (o.model != null)
                return false
        }
        else if (this.model != o.model)
            return false
        if (this.pic == null) {
            if (o.pic != null)
                return false
        }
        else if (this.pic != o.pic)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.pmsCode == null) 0 else this.pmsCode.hashCode())
        result = prime * result + (if (this.description == null) 0 else this.description.hashCode())
        result = prime * result + (if (this.place == null) 0 else this.place.hashCode())
        result = prime * result + (if (this.kind == null) 0 else this.kind.hashCode())
        result = prime * result + (if (this.scheduleKey == null) 0 else this.scheduleKey.hashCode())
        result = prime * result + (if (this.model == null) 0 else this.model.hashCode())
        result = prime * result + (if (this.pic == null) 0 else this.pic.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("Job (")

        sb.append(pmsCode)
        sb.append(", ").append(description)
        sb.append(", ").append(place)
        sb.append(", ").append(kind)
        sb.append(", ").append(scheduleKey)
        sb.append(", ").append(model)
        sb.append(", ").append(pic)

        sb.append(")")
        return sb.toString()
    }
}
