/*
 * This file is generated by jOOQ.
 */
package me.ave.inventory.jooq.codegen.tables.pojos


import java.io.Serializable

import javax.annotation.processing.Generated

import kotlinx.datetime.Instant


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.19.7",
        "schema version:public_2"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("UNCHECKED_CAST")
data class Machine(
    var model: String? = null,
    var machineNo: Int? = null,
    var lastMaintenance: Instant? = null,
    var avgRh: Int? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: Machine = other as Machine
        if (this.model == null) {
            if (o.model != null)
                return false
        }
        else if (this.model != o.model)
            return false
        if (this.machineNo == null) {
            if (o.machineNo != null)
                return false
        }
        else if (this.machineNo != o.machineNo)
            return false
        if (this.lastMaintenance == null) {
            if (o.lastMaintenance != null)
                return false
        }
        else if (this.lastMaintenance != o.lastMaintenance)
            return false
        if (this.avgRh == null) {
            if (o.avgRh != null)
                return false
        }
        else if (this.avgRh != o.avgRh)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.model == null) 0 else this.model.hashCode())
        result = prime * result + (if (this.machineNo == null) 0 else this.machineNo.hashCode())
        result = prime * result + (if (this.lastMaintenance == null) 0 else this.lastMaintenance.hashCode())
        result = prime * result + (if (this.avgRh == null) 0 else this.avgRh.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("Machine (")

        sb.append(model)
        sb.append(", ").append(machineNo)
        sb.append(", ").append(lastMaintenance)
        sb.append(", ").append(avgRh)

        sb.append(")")
        return sb.toString()
    }
}
