/*
 * This file is generated by jOOQ.
 */
package me.ave.inventory.jooq.codegen.tables.pojos


import java.io.Serializable

import javax.annotation.processing.Generated


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.19.7",
        "schema version:public_2"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("UNCHECKED_CAST")
data class Machinetolocation(
    var model: String? = null,
    var locationId: Int? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: Machinetolocation = other as Machinetolocation
        if (this.model == null) {
            if (o.model != null)
                return false
        }
        else if (this.model != o.model)
            return false
        if (this.locationId == null) {
            if (o.locationId != null)
                return false
        }
        else if (this.locationId != o.locationId)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.model == null) 0 else this.model.hashCode())
        result = prime * result + (if (this.locationId == null) 0 else this.locationId.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("Machinetolocation (")

        sb.append(model)
        sb.append(", ").append(locationId)

        sb.append(")")
        return sb.toString()
    }
}
