/*
 * This file is generated by jOOQ.
 */
package me.ave.inventory.jooq.codegen.tables.pojos


import java.io.Serializable

import javax.annotation.processing.Generated


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.19.7",
        "schema version:public_2"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("UNCHECKED_CAST")
data class Machineinfo(
    var model: String? = null,
    var name: String? = null,
    var maker: String? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: Machineinfo = other as Machineinfo
        if (this.model == null) {
            if (o.model != null)
                return false
        }
        else if (this.model != o.model)
            return false
        if (this.name == null) {
            if (o.name != null)
                return false
        }
        else if (this.name != o.name)
            return false
        if (this.maker == null) {
            if (o.maker != null)
                return false
        }
        else if (this.maker != o.maker)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.model == null) 0 else this.model.hashCode())
        result = prime * result + (if (this.name == null) 0 else this.name.hashCode())
        result = prime * result + (if (this.maker == null) 0 else this.maker.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("Machineinfo (")

        sb.append(model)
        sb.append(", ").append(name)
        sb.append(", ").append(maker)

        sb.append(")")
        return sb.toString()
    }
}
