/*
 * This file is generated by jOOQ.
 */
package me.ave.inventory.jooq.codegen.tables.pojos


import java.io.Serializable

import javax.annotation.processing.Generated


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.19.7",
        "schema version:public_2"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("UNCHECKED_CAST")
data class Maintenanceupdatedpacket(
    var maintenanceId: Int? = null,
    var sparePartCode: String? = null,
    var updatedQuantity: Int? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: Maintenanceupdatedpacket = other as Maintenanceupdatedpacket
        if (this.maintenanceId == null) {
            if (o.maintenanceId != null)
                return false
        }
        else if (this.maintenanceId != o.maintenanceId)
            return false
        if (this.sparePartCode == null) {
            if (o.sparePartCode != null)
                return false
        }
        else if (this.sparePartCode != o.sparePartCode)
            return false
        if (this.updatedQuantity == null) {
            if (o.updatedQuantity != null)
                return false
        }
        else if (this.updatedQuantity != o.updatedQuantity)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.maintenanceId == null) 0 else this.maintenanceId.hashCode())
        result = prime * result + (if (this.sparePartCode == null) 0 else this.sparePartCode.hashCode())
        result = prime * result + (if (this.updatedQuantity == null) 0 else this.updatedQuantity.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("Maintenanceupdatedpacket (")

        sb.append(maintenanceId)
        sb.append(", ").append(sparePartCode)
        sb.append(", ").append(updatedQuantity)

        sb.append(")")
        return sb.toString()
    }
}
