/*
 * This file is generated by jOOQ.
 */
package me.ave.inventory.jooq.codegen.tables.pojos


import java.io.Serializable

import javax.annotation.processing.Generated

import kotlinx.datetime.Instant


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.19.7",
        "schema version:public_2"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("UNCHECKED_CAST")
data class Maintenancerecord(
    var id: Int? = null,
    var model: String? = null,
    var machineNo: Int? = null,
    var pmsCode: String? = null,
    var timeStarted: Instant? = null,
    var timeCompleted: Instant? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: Maintenancerecord = other as Maintenancerecord
        if (this.id == null) {
            if (o.id != null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.model == null) {
            if (o.model != null)
                return false
        }
        else if (this.model != o.model)
            return false
        if (this.machineNo == null) {
            if (o.machineNo != null)
                return false
        }
        else if (this.machineNo != o.machineNo)
            return false
        if (this.pmsCode == null) {
            if (o.pmsCode != null)
                return false
        }
        else if (this.pmsCode != o.pmsCode)
            return false
        if (this.timeStarted == null) {
            if (o.timeStarted != null)
                return false
        }
        else if (this.timeStarted != o.timeStarted)
            return false
        if (this.timeCompleted == null) {
            if (o.timeCompleted != null)
                return false
        }
        else if (this.timeCompleted != o.timeCompleted)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id == null) 0 else this.id.hashCode())
        result = prime * result + (if (this.model == null) 0 else this.model.hashCode())
        result = prime * result + (if (this.machineNo == null) 0 else this.machineNo.hashCode())
        result = prime * result + (if (this.pmsCode == null) 0 else this.pmsCode.hashCode())
        result = prime * result + (if (this.timeStarted == null) 0 else this.timeStarted.hashCode())
        result = prime * result + (if (this.timeCompleted == null) 0 else this.timeCompleted.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("Maintenancerecord (")

        sb.append(id)
        sb.append(", ").append(model)
        sb.append(", ").append(machineNo)
        sb.append(", ").append(pmsCode)
        sb.append(", ").append(timeStarted)
        sb.append(", ").append(timeCompleted)

        sb.append(")")
        return sb.toString()
    }
}
