/*
 * This file is generated by jOOQ.
 */
package me.ave.inventory.jooq.codegen.tables.pojos


import java.io.Serializable

import javax.annotation.processing.Generated

import me.ave.inventory.jooq.codegen.enums.PacketType


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.19.7",
        "schema version:public_2"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("UNCHECKED_CAST")
data class Packetrecord(
    var id: Int? = null,
    var code: String? = null,
    var rfid: String? = null,
    var quantity: Int? = null,
    var type: PacketType? = null,
    var locationId: Int? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: Packetrecord = other as Packetrecord
        if (this.id == null) {
            if (o.id != null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.code == null) {
            if (o.code != null)
                return false
        }
        else if (this.code != o.code)
            return false
        if (this.rfid == null) {
            if (o.rfid != null)
                return false
        }
        else if (this.rfid != o.rfid)
            return false
        if (this.quantity == null) {
            if (o.quantity != null)
                return false
        }
        else if (this.quantity != o.quantity)
            return false
        if (this.type == null) {
            if (o.type != null)
                return false
        }
        else if (this.type != o.type)
            return false
        if (this.locationId == null) {
            if (o.locationId != null)
                return false
        }
        else if (this.locationId != o.locationId)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id == null) 0 else this.id.hashCode())
        result = prime * result + (if (this.code == null) 0 else this.code.hashCode())
        result = prime * result + (if (this.rfid == null) 0 else this.rfid.hashCode())
        result = prime * result + (if (this.quantity == null) 0 else this.quantity.hashCode())
        result = prime * result + (if (this.type == null) 0 else this.type.hashCode())
        result = prime * result + (if (this.locationId == null) 0 else this.locationId.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("Packetrecord (")

        sb.append(id)
        sb.append(", ").append(code)
        sb.append(", ").append(rfid)
        sb.append(", ").append(quantity)
        sb.append(", ").append(type)
        sb.append(", ").append(locationId)

        sb.append(")")
        return sb.toString()
    }
}
