/*
 * This file is generated by jOOQ.
 */
package me.ave.inventory.jooq.codegen.tables.pojos


import java.io.Serializable

import javax.annotation.processing.Generated


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.19.7",
        "schema version:public_2"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("UNCHECKED_CAST")
data class Usedpacketrecord(
    var id: Int? = null,
    var packetId: Int? = null,
    var maintenanceId: Int? = null,
    var quantity: Int? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: Usedpacketrecord = other as Usedpacketrecord
        if (this.id == null) {
            if (o.id != null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.packetId == null) {
            if (o.packetId != null)
                return false
        }
        else if (this.packetId != o.packetId)
            return false
        if (this.maintenanceId == null) {
            if (o.maintenanceId != null)
                return false
        }
        else if (this.maintenanceId != o.maintenanceId)
            return false
        if (this.quantity == null) {
            if (o.quantity != null)
                return false
        }
        else if (this.quantity != o.quantity)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id == null) 0 else this.id.hashCode())
        result = prime * result + (if (this.packetId == null) 0 else this.packetId.hashCode())
        result = prime * result + (if (this.maintenanceId == null) 0 else this.maintenanceId.hashCode())
        result = prime * result + (if (this.quantity == null) 0 else this.quantity.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("Usedpacketrecord (")

        sb.append(id)
        sb.append(", ").append(packetId)
        sb.append(", ").append(maintenanceId)
        sb.append(", ").append(quantity)

        sb.append(")")
        return sb.toString()
    }
}
